// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2stjjPE_ZLmoskjngSUfZm3lWEYzvYM',
    appId: '1:265739675454:web:0025bb5e56dba371a16e6f',
    messagingSenderId: '265739675454',
    projectId: 'krishisetu-73ac6',
    authDomain: 'krishisetu-73ac6.firebaseapp.com',
    storageBucket: 'krishisetu-73ac6.appspot.com',
    measurementId: 'G-4EF8VQX06H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8qLlIL5Xvj7LUR1s7ffdQPfG2scmKg0',
    appId: '1:265739675454:android:bfe0e46e1a3f2ec2a16e6f',
    messagingSenderId: '265739675454',
    projectId: 'krishisetu-73ac6',
    storageBucket: 'krishisetu-73ac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_v6Ejj1k4PFteUvvRIhHxu82Ck4g9Wo',
    appId: '1:265739675454:ios:21ec87a814714342a16e6f',
    messagingSenderId: '265739675454',
    projectId: 'krishisetu-73ac6',
    storageBucket: 'krishisetu-73ac6.appspot.com',
    iosBundleId: 'com.example.krishiSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_v6Ejj1k4PFteUvvRIhHxu82Ck4g9Wo',
    appId: '1:265739675454:ios:21ec87a814714342a16e6f',
    messagingSenderId: '265739675454',
    projectId: 'krishisetu-73ac6',
    storageBucket: 'krishisetu-73ac6.appspot.com',
    iosBundleId: 'com.example.krishiSetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh2stjjPE_ZLmoskjngSUfZm3lWEYzvYM',
    appId: '1:265739675454:web:ec3eb48562cb2b55a16e6f',
    messagingSenderId: '265739675454',
    projectId: 'krishisetu-73ac6',
    authDomain: 'krishisetu-73ac6.firebaseapp.com',
    storageBucket: 'krishisetu-73ac6.appspot.com',
    measurementId: 'G-RCGTTZDXFS',
  );
}
